sonar.projectKey=amex-shell
sonar.projectName=AMEX Shell
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000

sonar.token=sqp_10bebd2b35d6afc88d3976033e511bee5b15f73a
sonar.login=sqp_10bebd2b35d6afc88d3976033e511bee5b15f73a

sonar.sources=src
sonar.scm.disabled=true

sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/.angular/**,**/coverage/**,**/zap-report.xml

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/shell/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8

# ZAP — path relative to this properties file (inside shell/ folder)
sonar.zaproxy.reportPath=zap-report.xml
sonar.zaproxy.htmlReportPath=zap-report.html
