sonar.projectKey=amex-shell
sonar.projectName=AMEX Shell
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000

sonar.token=sqp_25d3ed2399d946ec1d90eaeb478f15448ea35957

sonar.sources=src/app

sonar.inclusions=**/*.ts,**/*.html,**/*.css

sonar.scm.exclusions.disabled=true

sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/.angular/**,**/coverage/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/shell/lcov.info

sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8

# ZAP Report
sonar.zaproxy.reportPath=zap-report.xml
