-- ANSI SQL — works on both H2 and PostgreSQL

CREATE TABLE IF NOT EXISTS members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_code VARCHAR(20)  NOT NULL,
    member_name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_members_client_code UNIQUE (client_code)
);

CREATE TABLE IF NOT EXISTS cards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT      NOT NULL,
    card_number VARCHAR(30) NOT NULL,
    card_type   VARCHAR(20) NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT uk_cards_card_number UNIQUE (card_number),
    CONSTRAINT fk_cards_member      FOREIGN KEY (member_id) REFERENCES members(id)
);

CREATE TABLE IF NOT EXISTS wearable_devices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id     BIGINT      NOT NULL,
    device_type VARCHAR(20) NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'Issued',
    issue_date  DATE        NOT NULL,
    serial_no   VARCHAR(50) NOT NULL,
    nfc_enabled BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_wearable_serial_no UNIQUE (serial_no),
    CONSTRAINT fk_devices_card       FOREIGN KEY (card_id) REFERENCES cards(id)
);