sonar.projectKey=amex-bta-portal
sonar.projectName=AMEX BTA Portal
sonar.projectVersion=1.0
 
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/.angular/**,**/coverage/**
 
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
 
sonar.javascript.lcov.reportPaths=coverage/bta-portal/lcov.info
 
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
